package coinbase

type CryptoCurrency string
type FiatCurrency string
type CurrencyPair string

type crypto struct {
	ALGO CryptoCurrency
	ATOM CryptoCurrency
	BAT  CryptoCurrency
	BTC  CryptoCurrency
	BCH  CryptoCurrency
	BSV  CryptoCurrency
	COMP CryptoCurrency
	CVC  CryptoCurrency
	DAI  CryptoCurrency
	DASH CryptoCurrency
	DNT  CryptoCurrency
	EOS  CryptoCurrency
	ETH  CryptoCurrency
	ETC  CryptoCurrency
	GNT  CryptoCurrency
	KNC  CryptoCurrency
	LINK CryptoCurrency
	LOOM CryptoCurrency
	LTC  CryptoCurrency
	MANA CryptoCurrency
	MKR  CryptoCurrency
	OMG  CryptoCurrency
	OXT  CryptoCurrency
	REP  CryptoCurrency
	USDC CryptoCurrency
	XLM  CryptoCurrency
	XRP  CryptoCurrency
	XTZ  CryptoCurrency
	ZEC  CryptoCurrency
	ZRX  CryptoCurrency
}

type fiat struct {
	AED FiatCurrency
	AFN FiatCurrency
	ALL FiatCurrency
	AMD FiatCurrency
	ANG FiatCurrency
	AOA FiatCurrency
	ARS FiatCurrency
	AUD FiatCurrency
	AWG FiatCurrency
	AZN FiatCurrency
	BAM FiatCurrency
	BBD FiatCurrency
	BDT FiatCurrency
	BGN FiatCurrency
	BHD FiatCurrency
	BIF FiatCurrency
	BMD FiatCurrency
	BND FiatCurrency
	BOB FiatCurrency
	BRL FiatCurrency
	BSD FiatCurrency
	BTN FiatCurrency
	BWP FiatCurrency
	BYN FiatCurrency
	BYR FiatCurrency
	BZD FiatCurrency
	CAD FiatCurrency
	CDF FiatCurrency
	CHF FiatCurrency
	CLF FiatCurrency
	CLP FiatCurrency
	CNH FiatCurrency
	CNY FiatCurrency
	COP FiatCurrency
	CRC FiatCurrency
	CUC FiatCurrency
	CVE FiatCurrency
	CZK FiatCurrency
	DJF FiatCurrency
	DKK FiatCurrency
	DOP FiatCurrency
	DZD FiatCurrency
	EEK FiatCurrency
	EGP FiatCurrency
	ERN FiatCurrency
	ETB FiatCurrency
	EUR FiatCurrency
	FJD FiatCurrency
	FKP FiatCurrency
	GBP FiatCurrency
	GEL FiatCurrency
	GGP FiatCurrency
	GHS FiatCurrency
	GIP FiatCurrency
	GMD FiatCurrency
	GNF FiatCurrency
	GTQ FiatCurrency
	GYD FiatCurrency
	HKD FiatCurrency
	HNL FiatCurrency
	HRK FiatCurrency
	HTG FiatCurrency
	HUF FiatCurrency
	IDR FiatCurrency
	ILS FiatCurrency
	IMP FiatCurrency
	INR FiatCurrency
	IQD FiatCurrency
	ISK FiatCurrency
	JEP FiatCurrency
	JMD FiatCurrency
	JOD FiatCurrency
	JPY FiatCurrency
	KES FiatCurrency
	KGS FiatCurrency
	KHR FiatCurrency
	KMF FiatCurrency
	KRW FiatCurrency
	KWD FiatCurrency
	KYD FiatCurrency
	KZT FiatCurrency
	LAK FiatCurrency
	LBP FiatCurrency
	LKR FiatCurrency
	LRD FiatCurrency
	LSL FiatCurrency
	LTL FiatCurrency
	LVL FiatCurrency
	LYD FiatCurrency
	MAD FiatCurrency
	MDL FiatCurrency
	MGA FiatCurrency
	MKD FiatCurrency
	MMK FiatCurrency
	MNT FiatCurrency
	MOP FiatCurrency
	MRO FiatCurrency
	MTL FiatCurrency
	MUR FiatCurrency
	MVR FiatCurrency
	MWK FiatCurrency
	MXN FiatCurrency
	MYR FiatCurrency
	MZN FiatCurrency
	NAD FiatCurrency
	NGN FiatCurrency
	NIO FiatCurrency
	NOK FiatCurrency
	NPR FiatCurrency
	NZD FiatCurrency
	OMR FiatCurrency
	PAB FiatCurrency
	PEN FiatCurrency
	PGK FiatCurrency
	PHP FiatCurrency
	PKR FiatCurrency
	PLN FiatCurrency
	PYG FiatCurrency
	QAR FiatCurrency
	RON FiatCurrency
	RSD FiatCurrency
	RUB FiatCurrency
	RWF FiatCurrency
	SAR FiatCurrency
	SBD FiatCurrency
	SCR FiatCurrency
	SEK FiatCurrency
	SGD FiatCurrency
	SHP FiatCurrency
	SLL FiatCurrency
	SOS FiatCurrency
	SRD FiatCurrency
	SSP FiatCurrency
	STD FiatCurrency
	SVC FiatCurrency
	SZL FiatCurrency
	THB FiatCurrency
	TJS FiatCurrency
	TMT FiatCurrency
	TND FiatCurrency
	TOP FiatCurrency
	TRY FiatCurrency
	TTD FiatCurrency
	TWD FiatCurrency
	TZS FiatCurrency
	UAH FiatCurrency
	UGX FiatCurrency
	USD FiatCurrency
	UYU FiatCurrency
	UZS FiatCurrency
	VEF FiatCurrency
	VES FiatCurrency
	VND FiatCurrency
	VUV FiatCurrency
	WST FiatCurrency
	XAF FiatCurrency
	XAG FiatCurrency
	XAU FiatCurrency
	XCD FiatCurrency
	XDR FiatCurrency
	XOF FiatCurrency
	XPD FiatCurrency
	XPF FiatCurrency
	XPT FiatCurrency
	YER FiatCurrency
	ZAR FiatCurrency
	ZMK FiatCurrency
	ZMW FiatCurrency
	ZWL FiatCurrency
}

type currencypairs struct {
	BAT_USDC  CurrencyPair
	BTC_EUR   CurrencyPair
	BTC_GBP   CurrencyPair
	BTC_USD   CurrencyPair
	ETH_BTC   CurrencyPair
	LINK_USDC CurrencyPair
}

var (
	Crypto = crypto {
		ALGO: "ALGO",
		ATOM: "ATOM",
		BAT:  "BAT",
		BTC:  "BTC",
		BCH:  "BCH",
		BSV:  "BSV",
		COMP: "COMP",
		CVC:  "CVC",
		DAI:  "DAI",
		DASH: "DASH",
		DNT:  "DNT",
		EOS:  "EOS",
		ETH:  "ETH",
		ETC:  "ETC",
		GNT:  "GNT",
		KNC:  "KNC",
		LINK: "LINK",
		LOOM: "LOOM",
		LTC:  "LTC",
		MANA: "MANA",
		MKR:  "MKR",
		OMG:  "OMG",
		OXT:  "OXT",
		REP:  "REP",
		USDC: "USDC",
		XLM:  "XLM",
		XRP:  "XRP",
		XTZ:  "XTZ",
		ZEC:  "ZEC",
		ZRX:  "ZRX",
	}

	Fiat = fiat {
		AED:  "AED",
		AFN:  "AFN",
		ALL:  "ALL",
		AMD:  "AMD",
		ANG:  "ANG",
		AOA:  "AOA",
		ARS:  "ARS",
		AUD:  "AUD",
		AWG:  "AWG",
		AZN:  "AZN",
		BAM:  "BAM",
		BBD:  "BBD",
		BDT:  "BDT",
		BGN:  "BGN",
		BHD:  "BHD",
		BIF:  "BIF",
		BMD:  "BMD",
		BND:  "BND",
		BOB:  "BOB",
		BRL:  "BRL",
		BSD:  "BSD",
		BTN:  "BTN",
		BWP:  "BWP",
		BYN:  "BYN",
		BYR:  "BYR",
		BZD:  "BZD",
		CAD:  "CAD",
		CDF:  "CDF",
		CHF:  "CHF",
		CLF:  "CLF",
		CLP:  "CLP",
		CNH:  "CNH",
		CNY:  "CNY",
		COP:  "COP",
		CRC:  "CRC",
		CUC:  "CUC",
		CVE:  "CVE",
		CZK:  "CZK",
		DJF:  "DJF",
		DKK:  "DKK",
		DOP:  "DOP",
		DZD:  "DZD",
		EEK:  "EEK",
		EGP:  "EGP",
		ERN:  "ERN",
		ETB:  "ETB",
		EUR:  "EUR",
		FJD:  "FJD",
		FKP:  "FKP",
		GBP:  "GBP",
		GEL:  "GEL",
		GGP:  "GGP",
		GHS:  "GHS",
		GIP:  "GIP",
		GMD:  "GMD",
		GNF:  "GNF",
		GTQ:  "GTQ",
		GYD:  "GYD",
		HKD:  "HKD",
		HNL:  "HNL",
		HRK:  "HRK",
		HTG:  "HTG",
		HUF:  "HUF",
		IDR:  "IDR",
		ILS:  "ILS",
		IMP:  "IMP",
		INR:  "INR",
		IQD:  "IQD",
		ISK:  "ISK",
		JEP:  "JEP",
		JMD:  "JMD",
		JOD:  "JOD",
		JPY:  "JPY",
		KES:  "KES",
		KGS:  "KGS",
		KHR:  "KHR",
		KMF:  "KMF",
		KRW:  "KRW",
		KWD:  "KWD",
		KYD:  "KYD",
		KZT:  "KZT",
		LAK:  "LAK",
		LBP:  "LBP",
		LKR:  "LKR",
		LRD:  "LRD",
		LSL:  "LSL",
		LTL:  "LTL",
		LVL:  "LVL",
		LYD:  "LYD",
		MAD:  "MAD",
		MDL:  "MDL",
		MGA:  "MGA",
		MKD:  "MKD",
		MMK:  "MMK",
		MNT:  "MNT",
		MOP:  "MOP",
		MRO:  "MRO",
		MTL:  "MTL",
		MUR:  "MUR",
		MVR:  "MVR",
		MWK:  "MWK",
		MXN:  "MXN",
		MYR:  "MYR",
		MZN:  "MZN",
		NAD:  "NAD",
		NGN:  "NGN",
		NIO:  "NIO",
		NOK:  "NOK",
		NPR:  "NPR",
		NZD:  "NZD",
		OMR:  "OMR",
		PAB:  "PAB",
		PEN:  "PEN",
		PGK:  "PGK",
		PHP:  "PHP",
		PKR:  "PKR",
		PLN:  "PLN",
		PYG:  "PYG",
		QAR:  "QAR",
		RON:  "RON",
		RSD:  "RSD",
		RUB:  "RUB",
		RWF:  "RWF",
		SAR:  "SAR",
		SBD:  "SBD",
		SCR:  "SCR",
		SEK:  "SEK",
		SGD:  "SGD",
		SHP:  "SHP",
		SLL:  "SLL",
		SOS:  "SOS",
		SRD:  "SRD",
		SSP:  "SSP",
		STD:  "STD",
		SVC:  "SVC",
		SZL:  "SZL",
		THB:  "THB",
		TJS:  "TJS",
		TMT:  "TMT",
		TND:  "TND",
		TOP:  "TOP",
		TRY:  "TRY",
		TTD:  "TTD",
		TWD:  "TWD",
		TZS:  "TZS",
		UAH:  "UAH",
		UGX:  "UGX",
		USD:  "USD",
		UYU:  "UYU",
		UZS:  "UZS",
		VEF:  "VEF",
		VES:  "VES",
		VND:  "VND",
		VUV:  "VUV",
		WST:  "WST",
		XAF:  "XAF",
		XAG:  "XAG",
		XAU:  "XAU",
		XCD:  "XCD",
		XDR:  "XDR",
		XOF:  "XOF",
		XPD:  "XPD",
		XPF:  "XPF",
		XPT:  "XPT",
		YER:  "YER",
		ZAR:  "ZAR",
		ZMK:  "ZMK",
		ZMW:  "ZMW",
		ZWL:  "ZWL",
	}

	CurrencyPairs = currencypairs {
		BAT_USDC:  "BAT-USDC",
		BTC_EUR:   "BTC-EUR",
		BTC_GBP:   "BTC-GBP",
		BTC_USD:   "BTC-USD",
		ETH_BTC:   "ETH-BTC",
		LINK_USDC: "LINK-USDC",
	}
)
